// use `TRANSFER.<name>` prefix for most cases

export const TRANSFER_ERROR = {
    DB_UNIQUE_VIOLATION: 'TRANSFER.DB.UNIQUE_VIOLATION',
    VALIDATION_ERROR: 'TRANSFER.VALIDATION_ERROR',
    WORKBOOK_EXPORT_NOT_EXIST: 'TRANSFER.WORKBOOK_EXPORT_NOT_EXIST',
    WORKBOOK_EXPORT_NOT_COMPLETED: 'TRANSFER.WORKBOOK_EXPORT_NOT_COMPLETED',
    WORKBOOK_EXPORT_DATA_OUTDATED: 'TRANSFER.WORKBOOK_EXPORT_DATA_OUTDATED',
    WORKBOOK_IMPORT_NOT_EXIST: 'TRANSFER.WORKBOOK_IMPORT_NOT_EXIST',
    WORKBOOK_OPERATION_FORBIDDEN: 'TRANSFER.WORKBOOK_OPERATION_FORBIDDEN',
    NO_USER_IN_CONTEXT: 'TRANSFER.NO_USER_IN_CONTEXT',
};
