// use `TRANSFER.<name>` prefix for most cases

export const TRANSFER_ERROR = {
    DB_UNIQUE_VIOLATION: 'TRANSFER.DB.UNIQUE_VIOLATION',
    VALIDATION_ERROR: 'TRANSFER.VALIDATION_ERROR',
    EXPORT_NOT_EXIST: 'TRANSFER.EXPORT_NOT_EXIST',
    IMPORT_NOT_EXIST: 'TRANSFER.IMPORT_NOT_EXIST',
};
