// use `META_MANAGER.<name>` prefix for most cases

export const META_MANAGER_ERROR = {
    DB_UNIQUE_VIOLATION: 'META_MANAGER.DB.UNIQUE_VIOLATION',
    VALIDATION_ERROR: 'META_MANAGER.VALIDATION_ERROR',
    WORKBOOK_EXPORT_NOT_EXIST: 'META_MANAGER.WORKBOOK_EXPORT_NOT_EXIST',
    WORKBOOK_EXPORT_NOT_COMPLETED: 'META_MANAGER.WORKBOOK_EXPORT_NOT_COMPLETED',
    WORKBOOK_EXPORT_DATA_OUTDATED: 'META_MANAGER.WORKBOOK_EXPORT_DATA_OUTDATED',
    WORKBOOK_IMPORT_NOT_EXIST: 'META_MANAGER.WORKBOOK_IMPORT_NOT_EXIST',
    WORKBOOK_OPERATION_FORBIDDEN: 'META_MANAGER.WORKBOOK_OPERATION_FORBIDDEN',
    WORKBOOK_ALREADY_EXISTS: 'META_MANAGER.WORKBOOK_ALREADY_EXISTS',
    WORKBOOK_NOT_EXIST: 'WORKBOOK_NOT_EXIST',
};
