export const META_MANAGER_NOTIFICATION_CODE = {
    UNEXPECTED_WORKFLOW_ERROR: 'UNEXPECTED_WORKFLOW_ERROR',
    SCOPE_NOT_AVAILABLE_FOR_INSTALLATION: 'SCOPE_NOT_AVAILABLE_FOR_INSTALLATION',
    WORKBOOK_EXPORT_CANCELLED: 'WORKBOOK_EXPORT_CANCELLED',
} as const;
